### PR TITLE
rename to sunxi_nand to avoid naming conflict

### PR DESCRIPTION
**Pull request by tisdall**
rename to sunxi_nand to avoid conflict with drivers/mtd/nand/nand.ko

discussion started here:  https://groups.google.com/d/topic/linux-sunxi/cYdLsiirve0/discussion

Essentially, with `sun7i_defconfig`, the sunxi_nand module never gets installed properly because it ends up having the same name as another kernel module.

### CODE REVIEW

**Comment by amery** [comment]
can you send it to the mailing list, with 3.4 in the subject, and CCed to me?

**Comment by tisdall** [comment]
I'm not sure I understand the request, but I generated a patch and sent it to the mailing list.

**Comment by tisdall** [comment]
this seems like a pretty straightforward fix, why the hold up?

Two modules have the same name, one needs to be changed.

**Comment by amery** [comment]
it was applied in the stage/sunxi-3.4 branch. if you can test that branch I can merge 3.4.102 and the patches there (including yours) to the sunxi-3.4 branch.

**Comment by tisdall** [comment]
@amery - I've been using that change since I posted it since I couldn't get sunxi_nand to load.  Unfortunately even after loading it doesn't work for my device, so I can only confirm that the change fixes the loading issue.  I'll see if I can find some time to recompile the kernel, but it's really just a filename change.

**Comment by tisdall** [comment]
this has been applied via the patch sent to the mailing list

**Pull request closed without merging**
