### PR TITLE
video: sun4i-lcd: add support LCD SPI module (thanks hipboi)

### PR DESCRIPTION
**Pull request by Quarx2k**
It's not broke devices without SPI.
Issue #38

### CODE REVIEW

**Comment by amery** [comment]
I'll try to merge the rest of hipboi's patch too

**Comment by amery** [comment]
done.... finally. can you test 6c01b6c84fff553672dc4c098eb62161e64597c7? It's the full patch from @hipboi, but I had to guess some parts as there is a gap between the codebase we have and the codebase where this commit was made.

**Comment by amery** [comment]
can you redo this patch to apply after 6c01b6c84 moving lcd_spi from mid9742 and aurora to the default `lcd0_panel_cfg`?

**Comment by Quarx2k** [comment]
H,. My commit doing the same,  moving  lcd_spi  to lcd0_panel_cfg

**Comment by amery** [comment]
@techn started splitting 6c01b6c84fff553672dc4c098eb62161e64597c7. we already have `lcd%d_bright` (ebc95e84d7a4a97043872743acc8332b6801a54f) and some cleanups (0165c7d303d8187e5cd0f20af270e1e03b648cbc, 0165c7d303d8187e5cd0f20af270e1e03b648cbc) but we need to find a way decent way to for `lcd_spi` without making it aurora specific.

**Comment by amery** [comment]
as of 0a3d1af067f5428c897e5423ccfef8f6c25456ec 3.0-v2 finally has lcd_spi support

**Comment by amery** [comment]
and the rest of the changes in the large patch are now on-hold on the `wip/linux-sunxi-3.0/disp` branch until the greenish hdmi output effect. so I'm closing this ticket.

**Pull request closed without merging**
