### PR TITLE
Initial Framebuffer console support

### PR DESCRIPTION
**Pull request by techn**
Fbcon support

Tested with MiniX and HDMI output

TODO
-Rotation
-Better support for different bpp than 32
-Performance improvements? Is current 8 framebuffers needed? hw blitting etc?

### CODE REVIEW

**Comment by hno** [comment]
Please fix your git identity.

**Comment by doozan** [comment]
I've cleaned up this patch here (no functional changes, I just simplified the multiple commits and removed the commits that messed with the whitespace): https://github.com/doozan/a10-rescue/tree/master/linux-kernel-patches

I find that this only only works when compiled into the kernel.  When loaded as a module, it crashes with the following:

```
(fb_videomode_to_var+0x0/0x78) from  (fbcon_debug_enter+0x78/0x1bc [fbcon])
(fbcon_debug_enter+0x78/0x1bc [fbcon]) from (fbcon_switch+0xf0/0x710 [fbcon])
(fbcon_switch+0xf0/0x710 [fbcon]) from  (redraw_screen+0x12c/0x200)
(redraw_screen+0x12c/0x200) from  (bind_con_driver+0x37c/0x3d4)
(bind_con_driver+0x37c/0x3d4) from  (take_over_console+0x3c/0x44)
(take_over_console+0x3c/0x44) from  (fbcon_takeover+0x58/0xac [fbcon])
(fbcon_takeover+0x58/0xac [fbcon]) from  (init_module+0x124/0x154 [fbcon])
(init_module+0x124/0x154 [fbcon]) from  (do_one_initcall+0x9c/0x16c)
(do_one_initcall+0x9c/0x16c) from  (sys_init_module+0x1628/0x17a0)
(sys_init_module+0x1628/0x17a0) from  (ret_fast_syscall+0x0/0x30)
```

Since this does not play well with the mali module, it would be idea to have them both available as modules that could be loaded/unloaded as needed.

**Comment by techn** [comment]
Thanks for testing. I'll check that module loading problem + cleanup pull request.
Currently I have been checking those TODO items.

**Comment by amery** [comment]
@techn please avoid C++ style comments and (as @hno mentioned before) fix your git identity to include your real name an mail address. thanks!

**Comment by techn** [comment]
@amery, I'll check comments also. I think identity should be fixed already?

**Comment by amery** [comment]
@techn: indeed, the identity is fixed. thanks! :-) ... I tried to make a noiseless patch (without the whitespace mess) at https://gist.github.com/3500413 which I'll be testing tonight on my mele and the a13-olinuxino, but there is a detail that bothers me. why do you remove the loop on `sel` in cmap and friends?

**Comment by techn** [comment]
@amery, You are true. Those are mistakes.. I'll include fix to cleanup commit which I'm currently testing.

**Comment by techn** [comment]
Did the cleanup. Tested as module and inside kernel.

**Comment by amery** [comment]
thank you! commited (after some minor style changes) as 3ca6f758e9cf89a44f6c4b0978c0c71dd3b18f9f

**Comment by ljbade** [comment]
I have been testing the fbcon support today on my Hackberry, with Ubuntu 12.04 core (armel compile).

There is a small issue related to interactive terminal editing of commands using arrows or backspace key (and same issue appears in some full screen console programs) where there pixels get all messed up like dirty/sticky pixels and is not corrected until something redraws the region to clear the dirty pixels.

Also the console can be rather slow when drawing a lot of text with scrolling, perhaps there is not hardware acceleration being used.

And finally the fbcon seems to be initialised very late in the kernel boot so that a lot of boot messages are not printed, and sometimes does not load until the very end of boot when init brings up the login prompt. Not sure if this is related to the display stuff being in a module or not?

**Comment by rzk** [comment]
I confirm the "sticky pixels" issue with fbcon, looks like framebuffer memory corruption of some sort.

Console is slow because it actually doesnt use anything except, hm, framebuffer. That why it is called fbcon (framebuffer console), right ? :) If you use board powered from AC adapter - check this http://linux-sunxi.org/Cpufreq Maybe you run your board with ondemand switching to 60Mhz which isnt enough even for console redrawing.

You can compile everything disp/fbcon related into kernel and have fbcon earlier, but due to our module order, it will be still some seconds before you will see something.

**Comment by ljbade** [comment]
I will try that cpufreq stuff to see if it runs faster. The Hackberry runs off AC so I might configure the kernel to always run at max frequency.

How do you change whether drivers are compiled into a module or into the kernel? I am new to linux kernel hacking.

**Comment by techn** [comment]
This should help you:
http://linux-sunxi.org/Framebuffer

2012/10/21 Leith Bade notifications@github.com

**Comment by ljbade** [comment]
Thanks for that, so I now understand that 'm' means, module and 'y' builtin.

So I have now set all the options to 'y'.

One thing I noticed is that the HDMI driver depends on the LCD driver? Is this needed as this board has only a HDMI connection and all the LCD stuff is disabled in the FEX file.

It means I can't turn off LCD and leave HDMI.

Final thing to figure out is how to change the module load order so display is started as early as possible.

EDIT:
I modified dev_hdmi.c and dev_lcd.c to use module_init rather than late_initcall.

This seems to make the display boot right at the start of the devices, after the subsystems and about the same time as the UART so I think it is as best as it can be done. Trying it with subsys_initcall caused the driver to fail to load the FEX config data.

**Comment by ljbade** [comment]
I wonder if the dirty pixels are caused by my kernel config using a ARGB format. I wonder if the transparency stuff has a bug somewhere.

**Comment by ljbade** [comment]
Looking through the code I have noticed a few problems.

First is indentation - someone has used tabs instead of spaces so the indenting is all messed up.

There is a mismatch long/int return value, a spelling mistake in the functions with timming, and some bad use of hardcoded ints rather than enum/defines to make it readable in a few places - big one is the from variable in fb_init, and the -1 return code in fb_ioctl.

fb_ioctl does not return -ENOTSUPP for default case.

fb_cursor should be removed entirely if it is not going to do anything so we can rely on default kernel soft-cursor.

fb_setcmap should be removed entirely (as it is a copy/paste of default kernel code), and the transparency & 0xFF mask should be moved into fb_setcolreg to catch cases where it is called instead of fb_setcmap.

fb_blank assumes everything other than power off case should turn display on, but misses the other blanking cases such as suspend vsync/hsync.

fb_pan_display lines 831-849 have some copy/paste and should be refactored outside of the if/else.

Also the code for setting screen_id is really confusing and messy in fb_init, perhaps lines 1503 - 1539 should be merged  with 1493. And what is up with line 1491, 1497, 1502, why does they use i and not screen_id?

**Comment by ljbade** [comment]
Ok so I have fixed up most of the stuff that I pointed out. How do I go about submitting this patch? Should I fork this then make another pull request?

**Comment by techn** [comment]
Great. :)
http://linux-sunxi.org/Submitting_patches

2012/10/22 Leith Bade notifications@github.com

**Comment by amery** [comment]
@ljbade: great, but please don't fix "indentation problems" unless you are actually fixing real code in that line. also be sure all new code follows Linux's style guidelines, that means tabs, not space and other things. Also please don't remove "dead code" that can be used to understand better how these chips work.

**Comment by polarcat** [comment]
@amery: the dead code can be simply ifdef'ed either with if 0 or e.g. with ifdef SUNXI_DEADCODE. But then again why we are afraid to remove dead code: you can always checkout "original" file from tag if you need to learn something from it. IMHO the less code we have to maintain the better.

**Comment by techn** [comment]
I think we should merge everything(72c0e433) we got from Allwinner before we can start re-factoring.

**Comment by ljbade** [comment]
Hmm, well I've removed the code in my local git, but you can always ifdef it out if you want to when you commit to the server.

Another bug I have changes is the hardware acceleration flags. Currently the flags are set to zero, which means two bugs:
First it should be set to a minimum of FBINFO_DEFAULT otherwise if you compile in the linux boot logo, and compile the drivers as a module then linux will crash (just search for FBINFO_MODULE)
Second FBINFO_HWACCEL_XPAN | FBINFO_HWACCEL_YPAN should be set otherwise the hardware scrolling in Fb_pan_display will never get called by fbcon.

I still have not tracked down the sticky pixels problem, but I did find a reference to some recent bugs in cfb_copyarea which seems the most likely culprit as the stickpixels happen when you use insert text into a line which I imagine calls this function. I am still investigating if this is the cause.

**Comment by ljbade** [comment]
I am also interested in what is required to implement hardware bitblt stuff for frame buffer.

What video memory acceleration does the A10 chip have? I see there is a 'g2d' device, and of course the mali stuff.

I guess I will have to look at the X acceleration stuff in mali.

**Comment by amery** [comment]
can we continue this talk in the mailing list? Please

**Comment by hno** [comment]
mån 2012-10-22 klockan 03:34 -0700 skrev Leith Bade:

> Hmm, well I've removed the code in my local git, but you can always
> ifdef it out if you want to when you commit to the server.

+1 on removing dead code imho. Especially if that code is already
ifdefed or commented out.

Most of the dead code ALlwinner have left around is really dead.
- Not working
- Often not matching the hardware at all

But make sure to split dead code removal from any bugfixes or
improvements in your commits.

Regards
Henrik

**Comment by amery** [comment]
On 22 October 2012 12:43, Henrik Nordström notifications@github.com wrote:

> mån 2012-10-22 klockan 03:34 -0700 skrev Leith Bade:
> 
> > Hmm, well I've removed the code in my local git, but you can always
> > ifdef it out if you want to when you commit to the server.
> 
> +1 on removing dead code imho. Especially if that code is already
> ifdefed or commented out.
> 
> Most of the dead code ALlwinner have left around is really dead.
> - Not working
> - Often not matching the hardware at all

I have nothing against removing dead code as long as it's not done
blindly, in many cases it's incomplete code more than hardware
unrelated code.

> But make sure to split dead code removal from any bugfixes or
> improvements in your commits.

yes, that was also part of the "spirit" of my previous comment.

**Comment by hno** [comment]
mån 2012-10-22 klockan 03:39 -0700 skrev Leith Bade:

> I am also interested in what is required to implement hardware bitblt
> stuff for frame buffer.

g2d does that, but it's sun4i (A10) only. A13 and A10s(A12) do not have
g2d unit.

> What video memory acceleration does the A10 chip have? I see there is
> a 'g2d' device, and of course the mali stuff.
> 
> I guess I will have to look at the X acceleration stuff in mali.

We can't really use mali from kernelspace. Depends on user libraries
where all the magic happens.

Regards
Henrik

**Comment by ljbade** [comment]
I have continued in the emailing list.

**Pull request closed without merging**
