### PR TITLE
Sunxi next

### PR DESCRIPTION
**Pull request by tandresen**

### CODE REVIEW

**Comment by tandresen** [comment]
updat

**Comment by wens** [comment]
What is this supposed to be?

**Comment by tandresen** [comment]
Hi,

I left my Laptopon Github open and my little son pressed a lot of button
there.
I hope nothing went wrong on the linux-sunxi github tree? I tried to close
these pull
request but it seems for me that everything is still fine. Am i right?
Sorry for this.

Kind regards
Tobias
2015-10-05 3:57 GMT+02:00 Chen-Yu Tsai notifications@github.com:

**Comment by wens** [comment]
No worries. Just wondering why a bunch of pull requests popped up for mainline linux stuff.

**Comment by chengwei920412** [comment]
OK.  Thank you. 

发自我的小米手机在 tandresen notifications@github.com，2015年10月5日 上午12:31写道：

You can view, comment on, or merge this pull request online at:
  https://github.com/linux-sunxi/linux-sunxi/pull/241

Commit Summary

  ARM: dts: sunxi: Add regulators for LeMaker BananaPi
  ARM: dts: sun6i: Columbus: Add i2c controller for communicating with the LCD
  ARM: dts: sun5i: Add simplefb node for tvencoder output
  ARM: dts: sun7i: Add regulator configuration to the pcduino3 dts file
  ARM: dts: sun8i: Add support for qt90h-v4 tablets
  ARM: dts: sun7i: Enable USB DRC on pcDuino 3
  ARM: dts: sun7i: Enable USB DRC on cubieboard2
  ARM: dts: sun5i: Add support for the Auxtek-T003 HDMI stick
  ARM: dts: sun6i: hummingbird: Add missing pinmux setting for gmac phy reset
  ARM: dts: sun4i: inet97fv2: Disable unused usb controllers
  ARM: dts: sun4i: inet97fv2: Add regulator nodes
  ARM: dts: sun4i: inet97fv2: Enable otg controller
  ARM: dts: sun4i: inet97fv2: Enable support for tablet keys
  ARM: dts: sun4i: inet97fv2: Enable i2c1 and i2c2 controllers
  ARM: dts: sun6i: Add lradc node
  ARM: dts: sun5i: Add dts file for inet98v_rev2 based tablets
  ARM: dts: sun6i: Add mmc2 pins for 8 bit emmc
  ARM: dts: sunxi: Add sun?i-q8-common.dtsi files for q8 tablets
  ARM: dts: sun4i: Add dts file inet9f-rev03 based tablets
  ARM: dts: sun4i: Add dts file for iNet-1 based tablets
  dts: sunxi: add eeprom to A10 OLinuXino Lime board
  dts: sunxi: correct vendor prefix on OLinuXino a10s micro
  dts: sunxi: add eeprom to A20 OLinuXino Lime board
  dts: sunxi: add eeprom to A20 OLinuXino Lime2 board
  dts: sunxi: add eeprom to A20 OLinuXino micro board
  ARM: dts: sun8i: Add new sun8i-a33-q8-tzx-723q4.dts file
  ARM: dts: sun5i: Add emac_pins_b definition
  ARM: dts: sun5i: Add dts file for the Wobo i5 top set box
  ARM: dts: sun6i: Add accelerometer on Columbus A31
  ARM: dts: sun7i: Add keypad clk node
  Merge branch 'sunxi/fixes-for-4.3' into sunxi/for-next
  Merge branch 'sunxi/dt-for-4.4' into sunxi/for-next
  Merge branch 'sunxi/defconfig-for-4.4' into sunxi/for-next
  Merge remote-tracking branch 'asoc/topic/sunxi' into sunxi-next
  can: Allwinner A10/A20 CAN Controller support - Devicetree bindings
  can: Allwinner A10/A20 CAN Controller support - Kernel module
  ARM: dts: sun8i: Add PWM controller node for A23/A33
  ARM: dts: sun8i: Add PWM channel 0 pinmux setting for A23/A33
  ARM: dts: sun5i: Add sun5i-q8-common.dtsi
  ARM: dts: sun5i: Add dts file for q8 formfactor a13 based tablets
  ARM: sun8i: Add the A33 AHB1 gates clock driver
  ARM: sun8i: Move A23 AHB1 gates out of common DTSI
  ARM: sun8i: A23: Add missing msgbox gate
  Merge commit '0738eff14d81' into sunxi-next
  Merge branches 'sunxi/clocks-for-4.4', 'sunxi/core-for-4.4', 'sunxi/defconfig-for-4.4' and 'sunxi/dt-for-4.4' into sunxi/for-next
  ARM: dts: sun8i: Add pwm-backlight device for A23/A33 Q8 format tablets
  Merge branch 'sunxi/dt-for-4.4' into sunxi/for-next
  Merge branch 'sunxi/for-next' into sunxi-next
  Merge tag 'v4.3-rc2' into sunxi-next
  Merge commit 'bde6f9ded1bd' into sunxi-next
  Merge commit '32dedbc22e44' into sunxi-next
  Merge pull request #1 from linux-sunxi/sunxi-next

File Changes

```
A
Documentation/devicetree/bindings/net/can/sun4i_can.txt
(36)


M
Documentation/devicetree/bindings/net/cpsw.txt
(7)


A
Documentation/devicetree/bindings/sound/sun4i-codec.txt
(33)


M
MAINTAINERS
(2)


M
arch/arm/boot/dts/Makefile
(10)


M
arch/arm/boot/dts/sun4i-a10-chuwi-v7-cw0825.dts
(12)


A
arch/arm/boot/dts/sun4i-a10-inet1.dts
(226)


M
arch/arm/boot/dts/sun4i-a10-inet97fv2.dts
(117)


A
arch/arm/boot/dts/sun4i-a10-inet9f-rev03.dts
(227)


M
arch/arm/boot/dts/sun4i-a10-jesurun-q5.dts
(15)


M
arch/arm/boot/dts/sun4i-a10-olinuxino-lime.dts
(12)


A
arch/arm/boot/dts/sun5i-a10s-auxtek-t003.dts
(159)


M
arch/arm/boot/dts/sun5i-a10s-olinuxino-micro.dts
(2)


A
arch/arm/boot/dts/sun5i-a10s-wobo-i5.dts
(224)


M
arch/arm/boot/dts/sun5i-a10s.dtsi
(20)


A
arch/arm/boot/dts/sun5i-a13-inet-98v-rev2.dts
(227)


A
arch/arm/boot/dts/sun5i-a13-q8-tablet.dts
(60)


A
arch/arm/boot/dts/sun5i-q8-common.dtsi
(170)


M
arch/arm/boot/dts/sun6i-a31-colombus.dts
(24)


M
arch/arm/boot/dts/sun6i-a31-hummingbird.dts
(9)


M
arch/arm/boot/dts/sun6i-a31.dtsi
(17)


M
arch/arm/boot/dts/sun7i-a20-bananapi.dts
(35)


M
arch/arm/boot/dts/sun7i-a20-cubieboard2.dts
(19)


M
arch/arm/boot/dts/sun7i-a20-olinuxino-lime.dts
(12)


M
arch/arm/boot/dts/sun7i-a20-olinuxino-lime2.dts
(47)


M
arch/arm/boot/dts/sun7i-a20-olinuxino-micro.dts
(6)


M
arch/arm/boot/dts/sun7i-a20-pcduino3.dts
(54)


M
arch/arm/boot/dts/sun7i-a20.dtsi
(10)


M
arch/arm/boot/dts/sun8i-a23-a33.dtsi
(40)


A
arch/arm/boot/dts/sun8i-a23-gt90h-v4.dts
(145)


M
arch/arm/boot/dts/sun8i-a23-ippo-q8h-v5.dts
(76)


M
arch/arm/boot/dts/sun8i-a23.dtsi
(25)


M
arch/arm/boot/dts/sun8i-a33-ippo-q8h-v1.2.dts
(70)


A
arch/arm/boot/dts/sun8i-a33-q8-tzx-723q4.dts
(70)


M
arch/arm/boot/dts/sun8i-a33.dtsi
(27)


A
arch/arm/boot/dts/sun8i-q8-common.dtsi
(97)


A
arch/arm/boot/dts/sunxi-q8-common.dtsi
(77)


M
arch/arm/configs/multi_v7_defconfig
(1)


M
arch/arm/configs/sunxi_defconfig
(4)


M
arch/arm64/boot/dts/apm/apm-storm.dtsi
(28)


M
drivers/clk/sunxi/clk-simple-gates.c
(2)


M
drivers/mmc/card/block.c
(206)


M
drivers/mmc/core/core.c
(23)


M
drivers/mmc/core/debugfs.c
(19)


M
drivers/mmc/core/host.c
(4)


M
drivers/mmc/core/mmc_ops.c
(1)


M
drivers/mmc/core/mmc_ops.h
(3)


M
drivers/mmc/core/pwrseq_emmc.c
(2)


M
drivers/mmc/core/pwrseq_simple.c
(45)


M
drivers/mmc/core/sd.c
(2)


M
drivers/mmc/core/sdio.c
(20)


M
drivers/mmc/core/sdio_ops.h
(7)


M
drivers/mmc/host/mmc_spi.c
(1)


M
drivers/mmc/host/moxart-mmc.c
(1)


M
drivers/mmc/host/mtk-sd.c
(2)


M
drivers/mmc/host/omap.c
(1)


M
drivers/mmc/host/sdhci-acpi.c
(1)


M
drivers/mmc/host/sdhci-bcm-kona.c
(2)


M
drivers/mmc/host/sdhci-of-at91.c
(1)


M
drivers/mmc/host/sdhci-of-esdhc.c
(3)


M
drivers/mmc/host/sdhci-pltfm.c
(6)


M
drivers/mmc/host/sdhci.c
(22)


M
drivers/mmc/host/sunxi-mmc.c
(8)


M
drivers/mmc/host/vub300.c
(6)


M
drivers/mmc/host/wbsd.c
(2)


M
drivers/net/bonding/bond_main.c
(4)


M
drivers/net/can/Kconfig
(10)


M
drivers/net/can/Makefile
(1)


A
drivers/net/can/sun4i_can.c
(857)


M
drivers/net/dsa/mv88e6xxx.c
(151)


M
drivers/net/dsa/mv88e6xxx.h
(8)


M
drivers/net/ethernet/apm/xgene/xgene_enet_hw.c
(3)


M
drivers/net/ethernet/apm/xgene/xgene_enet_main.c
(16)


M
drivers/net/ethernet/apm/xgene/xgene_enet_main.h
(5)


M
drivers/net/ethernet/intel/fm10k/fm10k_debugfs.c
(5)


M
drivers/net/ethernet/intel/fm10k/fm10k_iov.c
(3)


M
drivers/net/ethernet/intel/fm10k/fm10k_main.c
(12)


M
drivers/net/ethernet/intel/fm10k/fm10k_netdev.c
(39)


M
drivers/net/ethernet/intel/fm10k/fm10k_pci.c
(176)


M
drivers/net/ethernet/intel/fm10k/fm10k_pf.c
(105)


M
drivers/net/ethernet/intel/fm10k/fm10k_type.h
(1)


M
drivers/net/ethernet/intel/fm10k/fm10k_vf.c
(14)


M
drivers/net/ethernet/intel/ixgbe/ixgbe.h
(3)


M
drivers/net/ethernet/intel/ixgbe/ixgbe_ethtool.c
(2)


M
drivers/net/ethernet/intel/ixgbe/ixgbe_lib.c
(2)


M
drivers/net/ethernet/intel/ixgbe/ixgbe_main.c
(25)


M
drivers/net/ethernet/marvell/mv643xx_eth.c
(43)


M
drivers/net/ethernet/smsc/smc91x.c
(29)


M
drivers/net/ethernet/smsc/smc91x.h
(99)


M
drivers/net/ethernet/ti/cpsw.c
(9)


M
drivers/net/usb/Kconfig
(2)


M
drivers/net/usb/cdc-phonet.c
(27)


M
drivers/net/usb/cdc_ether.c
(230)


M
drivers/net/usb/cdc_ncm.c
(69)


M
drivers/net/usb/qmi_wwan.c
(66)


M
drivers/net/usb/usbnet.c
(138)


M
drivers/net/vrf.c
(11)


M
include/linux/mmc/core.h
(2)


M
include/linux/netdevice.h
(14)


M
include/linux/netfilter.h
(68)


M
include/linux/netfilter_bridge.h
(2)


M
include/linux/netfilter_ingress.h
(2)


M
include/linux/tcp.h
(1)


A
include/linux/usb/cdc.h
(51)


M
include/net/dn_neigh.h
(6)


M
include/net/dst.h
(6)


M
include/net/ipv6.h
(2)


M
include/net/netfilter/br_netfilter.h
(2)


M
include/net/route.h
(2)


M
include/net/rtnetlink.h
(3)


M
include/net/sch_generic.h
(3)


M
include/net/sock.h
(12)


M
include/net/xfrm.h
(2)


M
include/uapi/linux/bpf.h
(9)


M
include/uapi/linux/mmc/ioctl.h
(19)


M
include/uapi/linux/pkt_cls.h
(4)


M
include/uapi/linux/rtnetlink.h
(2)


M
include/uapi/linux/usb/cdc.h
(6)


M
net/bridge/br_forward.c
(16)


M
net/bridge/br_input.c
(25)


M
net/bridge/br_multicast.c
(4)


M
net/bridge/br_netfilter_hooks.c
(54)


M
net/bridge/br_netfilter_ipv6.c
(8)


M
net/bridge/br_private.h
(6)


M
net/bridge/br_stp_bpdu.c
(12)


M
net/bridge/netfilter/ebtable_filter.c
(4)


M
net/bridge/netfilter/ebtable_nat.c
(4)


M
net/core/dev.c
(20)


M
net/core/filter.c
(58)


M
net/core/net-sysfs.c
(9)


M
net/core/rtnetlink.c
(2)


M
net/decnet/dn_neigh.c
(23)


M
net/decnet/dn_nsp_in.c
(7)


M
net/decnet/dn_nsp_out.c
(4)


M
net/decnet/dn_route.c
(30)


M
net/ipv4/af_inet.c
(16)


M
net/ipv4/arp.c
(20)


M
net/ipv4/devinet.c
(3)


M
net/ipv4/ip_forward.c
(19)


M
net/ipv4/ip_input.c
(39)


M
net/ipv4/ip_output.c
(58)


M
net/ipv4/ip_vti.c
(2)


M
net/ipv4/ipmr.c
(15)


M
net/ipv4/netfilter/arptable_filter.c
(4)


M
net/ipv4/netfilter/ip_tables.c
(8)


M
net/ipv4/netfilter/ipt_CLUSTERIP.c
(2)


M
net/ipv4/netfilter/ipt_SYNPROXY.c
(2)


M
net/ipv4/netfilter/iptable_filter.c
(6)


M
net/ipv4/netfilter/iptable_mangle.c
(7)


M
net/ipv4/netfilter/iptable_nat.c
(5)


M
net/ipv4/netfilter/iptable_raw.c
(6)


M
net/ipv4/netfilter/iptable_security.c
(5)


M
net/ipv4/netfilter/nf_conntrack_l3proto_ipv4.c
(4)


M
net/ipv4/raw.c
(5)


M
net/ipv4/route.c
(107)


M
net/ipv4/tcp_input.c
(1)


M
net/ipv4/tcp_ipv4.c
(2)


M
net/ipv4/tcp_output.c
(2)


M
net/ipv4/xfrm4_input.c
(7)


M
net/ipv4/xfrm4_output.c
(11)


M
net/ipv4/xfrm4_policy.c
(1)


M
net/ipv6/addrconf.c
(13)


M
net/ipv6/ip6_input.c
(15)


M
net/ipv6/ip6_output.c
(38)


M
net/ipv6/ip6_vti.c
(2)


M
net/ipv6/ip6mr.c
(12)


M
net/ipv6/mcast.c
(9)


M
net/ipv6/ndisc.c
(6)


M
net/ipv6/netfilter/ip6_tables.c
(8)


M
net/ipv6/netfilter/ip6t_SYNPROXY.c
(2)


M
net/ipv6/netfilter/ip6table_filter.c
(5)


M
net/ipv6/netfilter/ip6table_mangle.c
(6)


M
net/ipv6/netfilter/ip6table_nat.c
(5)


M
net/ipv6/netfilter/ip6table_raw.c
(5)


M
net/ipv6/netfilter/ip6table_security.c
(4)


M
net/ipv6/netfilter/nf_conntrack_l3proto_ipv6.c
(4)


M
net/ipv6/netfilter/nf_defrag_ipv6_hooks.c
(2)


M
net/ipv6/output_core.c
(8)


M
net/ipv6/raw.c
(9)


M
net/ipv6/tcp_ipv6.c
(2)


M
net/ipv6/xfrm6_input.c
(4)


M
net/ipv6/xfrm6_output.c
(11)


M
net/netfilter/ipvs/ip_vs_xmit.c
(8)


M
net/netfilter/nf_queue.c
(2)


M
net/netfilter/nfnetlink_queue_core.c
(3)


M
net/sched/act_bpf.c
(1)


M
net/sched/cls_bpf.c
(61)


M
net/xfrm/xfrm_output.c
(18)


M
net/xfrm/xfrm_policy.c
(4)


M
samples/bpf/bpf_helpers.h
(4)


M
samples/bpf/tcbpf1_kern.c
(24)


M
sound/soc/Kconfig
(1)


M
sound/soc/Makefile
(1)


A
sound/soc/sunxi/Kconfig
(11)


A
sound/soc/sunxi/Makefile
(2)


A
sound/soc/sunxi/sun4i-codec.c
(0)
```

Patch Links:

  https://github.com/linux-sunxi/linux-sunxi/pull/241.patch
  https://github.com/linux-sunxi/linux-sunxi/pull/241.diff

**Pull request closed without merging**
