### PR TITLE
Attempting minor performance enhancement of the A10 wemac NIC driver

### PR DESCRIPTION
**Pull request by lundman**
I have the ICS4 20120609 image on Mele A2000 and there are some networking issues with the wired 'wemac' NIC. It can not quite stream videos that it can otherwise play perfectly from local storage.

Using the amery 3.0.31+ branch from github, and no other changes (no tweaking, or network settings)
I did a simple network test based on:

```
# time wget -O /dev/null http://192.168.30.44:8001/testfile.bin
```

(from Mac Pro running OSX 10.7.3 with llink-2.3.2). Not the best test perhaps, but gave me a good indicator.

Result from 10 such tests were:
2012-06-19 09:33:53 (3.55 MB/s) - `/dev/null' saved [114720238/114720238]
real    0m21.040s
real    0m15.308s
real    0m27.234s
real    0m15.715s
real    0m21.850s
real    0m35.226s
real    0m20.613s
real    0m42.949s
real    0m14.064s
real    0m16.241s

Pretty fluctuating. From 14s to 42s. In fact, it struggles to start, once the tcp.win size starts to increase, it generally finds its feet, and when it hits 5Mb/s to goes up to 9Mb/s without issues.

First thing I noticed in drivers/net/sun4i/sun4i_wemac.c is the CPU Busyloop. I guess some debug 'delay' hack that was left in. 

```
-               for(i=0;i<1000;i++);
+               //for(i=0;i<1000;i++);
```

and test again:

2012-06-19 09:44:48 (7.69 MB/s) - `/dev/null' saved [114720238/114720238]
real    0m14.499s
sys     0m13.950s
real    0m20.611s
real    0m18.529s  
real    0m16.415s
real    0m18.042s
real    0m23.971s
real    0m24.729s
real    0m20.156s
real    0m19.658s

Which is a little better. More stable, but still fluctuating somewhat. I noticed the RX DMA interrupt handler has some udelay(100) code, I try halving them to 50:

real    0m15.632s
real    0m18.445s
real    0m15.785s
real    0m49.516s
real    0m15.115s
real    0m13.810s
real    0m38.116s
real    0m15.428s
real    0m17.187s
real    0m22.096s

That appears to have made it worse. So finally, I change udelay(100) to udelay(150):

real    0m12.270s
real    0m12.248s
real    0m12.138s
real    0m12.155s
real    0m12.145s
real    0m12.159s
real    0m12.182s
real    0m12.122s
real    0m12.533s
real    0m12.134s

Perfect. It no longer struggles, and just starts at 5Mb/s and goes directly to 9Mb/s. This could be somewhat "tweaked" specifically for the Mele A2000 (my hardware) but it sure makes it perform better. I really want to try the ICS4 kernel with this change, but I do not know how to build/boot such a kernel.

### CODE REVIEW

**Comment by hno** [comment]
Please do not use // comments. C99 comments is not allowed in kernel.

Also may be worth looking into why wemac_msleep() is commented out replaced by an udelay.

**Comment by amery** [comment]
I just merged this (with C comments) as 43877b5458d424394f1367fbde03aa9ec9939f5f, but waiting for some feedback about `wemac_msleep()`

**Comment by lundman** [comment]
Ok, it took a lot of time, but I got the NIC to a state where it works. I can stream 1080p video in ICS4 without stutter. Performance reached about 11.3mB/s (with tweaking buffers). I removed some stale code, and fixed comments. Since I am now pleased with the performance of the NIC, I have no current plans to make more changes.

**Comment by amery** [comment]
@lundman: I'm confused... beside comments clean up, what's the real change?

**Comment by Vayu** [comment]
I believe it is not such a good idea to remove comments and do actual code changes in the same commit. It makes it very hard to see what is going on.

Another question if wemac NIC is capable of using DMA in principle. If yes, then comments (which seem to be an attempt to utilize DMA in the driver) should be kept as hints for whoever might try to fix it later. It would be a really good thing to use DMA, since now driver eats CPU as crazy.

**Comment by amery** [comment]
+1 @Vayu

**Comment by lundman** [comment]
Hello everyone.

My primary goal was to remove the udelay()s as I was fairly confident that they are in fact the cause of the stutter. Comparing with dm9000, you can see "they" handle the reading of the IOport using:
https://github.com/amery/linux-allwinner/blob/allwinner-v3.0-android-v2/drivers/net/dm9000.c#L947

Now clearly someone at "sun4i" had the same problem, but went for udelay() and re-read. Naturally, I wished to try the dm9000 way, without the udelay() call. This made a world of difference.

: what if Rxcount is still zero after the second readl?

Exactly the same as in the original "sun4i" driver udelay, and indeed, dm9000. It goes does to the DM9000_PKT_RDY test, and fails, return. No logic change here, just removal of udelay() and always read register twice.

: I believe it is not such a good idea to remove comments

I agree, but it was you guys that went on about comments with the first revision. Even though these comments aren't mine, I thought I would "do one for the team" and change them to correct comments. Personally, I care not which comment style is used, and find the distinction irrelevant.

: if wemac NIC is capable of using DMA in principle. 

Actually, I retract my earlier comment about DMA. The sun4i/readme claims it does not do DMA, but it most certainly is. I thought all the DMA functions at the top of the file was not in use, but they are. See here:

https://github.com/amery/linux-allwinner/blob/allwinner-v3.0-android-v2/drivers/net/sun4i/sun4i_wemac.c#L1380
https://github.com/amery/linux-allwinner/blob/allwinner-v3.0-android-v2/drivers/net/sun4i/sun4i_wemac.c#L1713

With the udelay() removed, I no longer feel it "eats CPU as crazy". In fact, playing Planet Earth 1080p over nic appears to take 9% CPU, the top process is "mediaserver".

User 10%, System 5%, IOW 0%, IRQ 1%
User 37 + Nice 0 + Sys 20 + Idle 276 + IOW 0 + IRQ 1 + SIRQ 3 = 337

I also brought in the wemac_msleep() function, as per preference from You. However, all it does is pick a different sleep based on "suspended". I don't think the suspended functionality is even enabled, so it is really irrelevant. Perhaps suspend feature wants to be enabled in future.

I did change some of the "hardcoded integers" to use #defined register names instead. Far from complete, just did the areas I was trying to understand. I think this makes it easier to read, and could certainly be done more.

Finally, removing the copyright notice is a big no-no, I have no idea how that happened, but I did copy in bulk from dm9000.h. I will fix this now.

**Comment by Vayu** [comment]
So there are 4 different changes here
1. Removing for-loop delay and changing the delays (already merged)
2. Removing delay after dummy read
3. Changing udelay to msleep or wemac_msleep
4. Comments

I did some tests of the point 2. I kept the **if** statement though, so only removed udelay inside it on the line https://github.com/amery/linux-allwinner/blob/allwinner-v3.0-android-v2/drivers/net/sun4i/sun4i_wemac.c#L1271

It does indeed help
here is iperf result **before** the change (~95% peak cpu load):
[ ID] Interval       Transfer     Bandwidth
[  4]  0.0-60.0 sec   553 MBytes  77.3 Mbits/sec

and **after**, the peak cpu load drops to 70%, also the throughput increases
[ ID] Interval       Transfer     Bandwidth
[  4]  0.0-60.1 sec   649 MBytes  90.6 Mbits/sec

I will have a look at the delays and do some tests with them later.

**Comment by amery** [comment]
@lundman: about the comments, we indeed need to get rid of the `//` comments, but not removing them, but turning them into `/* ... */` and `#if 0 ... #endif` blocks, so we _preserve_ the comments and the disabled code but in C style ;-)

**Comment by lundman** [comment]
I didn't remove any comments. But I did remove some dead code, functions not used, and debug code commented out, and large chunk of commented-out-code that does not work (doesn't compile, or is for the wrong chipset). That is true. Any particular reason to leave that around? Nostalgia? The whole file looks like a debug party that was never cleaned up...

**Comment by Vayu** [comment]
@lundman I'd say just leave it for now, because the party is not over.

@all
I've been playing with wemac_rx function and managed to get peak CPU usage down to 50%, but eventually breaking it (can't fix it until Monday). Here are some observations.

I've stumbled upon serious problems with UDP in this driver. It would be very nice if other people checked it as well. At some speeds it drops 100% of packets, also filling kernel log with various complaints. Here how you do it:
on mele > ipref -s -u
on other machine > iperf -c mele.lan -u -t 60 -b 100m
where 100m is speed, please try 70m and 50m too (preferably while mele is not under load)

It seems that the problem is related to the fact that UDP has no congestion control and packets can come in big bunches + some timing issues. But any sensible network driver should be able to handle such situations (my nslu2 box has no problems with UDP).

Another thing is DMA. It is true that there is some attempt to use DMA for receiving data, but it won't works by the looks of it. There is a threshold of 2000 bytes of packet size and it is never reached using TCP.

If someone can confirm that DMA is working (or not) it would be quite useful. The idea is simple:
1. you look at the number of DMA interrupts in "cat /proc/interrupts"
2. run some heavy network stuff, which does not trigger DMA in other parts of the system (so no reading flash, and possibly no USB disks). iperf is OK. Streaming stuff to/form /dev/zero should be also fine.
3. check "cat /proc/interrupts" again

In my case TCP congestion works well to keep packets under 2000, so DMA is never used. And UDP is broken both ways (with and without DMA).

**Comment by Vayu** [comment]
To summarize digging through wemac driver.
The current result for TCP receiving test is 92.6 Mbit/s at 38% avg CPU load. It is still without using DMA.

DMA for transmitting is commented out. DMA for receiving is present but never used, because the threshold is larger than any valid Fast Ethernet frame (which is 1518) here https://github.com/amery/linux-allwinner/blob/allwinner-v3.0-android-v2/drivers/net/sun4i/sun4i_wemac.c#L56

One can lower this value and it even works, but it is not true DMA. It is just telling DMA controller to read buffer from NIC IO ports, thus 2 interrupts per packet - awfully slow. The real boost could be from using DMA ring buffer, and using polling NAPI, but this is beyond guessing, we need docs.

Also, as much as I struggled to make UDP working, at high speeds (>50Mbit) it quickly trashes the receiver and driver can only keep resetting the FIFO. It feels like Ethernet flow control does not work, or works only partially. Also the best way to clear overrun queue is unknown (delays, etc).

Further improvements are hindered by the lack of documentation on the chip and its registers. I know anyone can write a driver given a datasheet, but guessing what each bit in each register does is just not fun.

**Comment by amery** [comment]
Thank you @lundman, I split it and merged the code fixing parts as 9290665dd3c5cf32843807bffea282dbfd48ee74

**Pull request closed without merging**
