### PR TITLE
Allwinner v3.0 android v2 merge sun4i/sun5i nand driver

### PR DESCRIPTION
**Pull request by EnJens**
Done as a pull request since It's quite a large change (files changed). 
Arguments for doing this in this branch:
- We still have changes to these drivers (most recent is the expose MBR part patch) - no reason to double the work.
- Drivers are 100% identical (only name differences)

One downside is that current configs will end up with no nand. I attempted to get SUN4I_NANDFLASH/SUN5I_NANDFLASH to autoselect SUNXI_NANDFLASH, but no luck so far. So users have to manually reselect it.

### CODE REVIEW

**Comment by amery** [comment]
for 3.0 I believe it's critical to not break .config compatibiliy. using a select should make this easily.

btw, in 3.4 the joined var is called SUNXI_NAND, but I‘m fine with keeping the FLASH part too

**Comment by EnJens** [comment]
You'd think so - for some reason what happens instead is: SUN5I_NANDFLASH gets disabled instead of SUNXI_NANDFLASH getting enabled.

Perhaps moving to SUNXI_NAND is better then :) Consistency and all.

**Comment by amery** [comment]
for the sake of consistency I backported the merge from 3.4 (a639ebedf138807b7a10cc3a585443e877ef9ea8), and then added a little change (de29f033102d33c947d5fe4542fe5c39528b852c) to preserve `.config`. It's seems to be working fine, so I'm closing the ticket ;-)

**Comment by Abirosvaldo** [comment]
hi,
I have the source code android to device A10s.

I can generate the image, at compile time  does not give any error.
I use program LiveSuit to record in memory Nand.
when I call the device appears the image of  "initlogo.rle", the image disappears, but not give sequence.

**Pull request closed without merging**
