### PR TITLE
SmartassV2 governor

### PR DESCRIPTION
**Pull request by christiantroy**
I'm using it in CM9 and AOKP porting since a month and it seems stable and responsive, less power hungry then "fantasy".

### CODE REVIEW

**Comment by christiantroy** [comment]
damn it took in too much stuff, sorry I'm redoing it

**Comment by amery** [comment]
I would cherrypicking the one commit alone anyway. I'm not a fan of Github "pull requests".... but... can you change it to use C comments only? `/* */`

**Comment by christiantroy** [comment]
https://github.com/christiantroy/linux-allwinner/commit/82f52f61354a9cf769b77b8e74b7b1497dcce0f3

done

**Comment by amery** [comment]
thanks, picked as 67aaa26dab7f7345864e774ffc3be382218f1090

**Pull request closed without merging**
