### PR TITLE
Reserve memory only when needed

### PR DESCRIPTION
**Pull request by davidgiven**
See: https://github.com/amery/linux-allwinner/issues/18

### CODE REVIEW

**Comment by amery** [comment]
can you remove the `#ifdef`s from those ugly?

``` c
#ifdef FOO
if (foo) {
...
}
#endif
```

if `foo` is `#define`d 0 dead code elimination will take those sections out

**Comment by davidgiven** [comment]
Do you mean the section at the bottom where it prints out the reserved memory blocks? If, e.g., USE_G2D isn't defined, then the g2d_start/g2d_size symbols aren't defined at all. I didn't want to #define them as 0 so as to clearly distinguish between the case when they're defined but set to 0 and the case when they're undefined. I'm happy to change it if you're sure, though.

**Comment by amery** [comment]
I personally hate `#ifdef`s within C functions, but I'll wait for more feedback

**Comment by steev** [comment]
Instead of the 
#if defined CONFIG || CONFIG 
  #define BLAH
#endif

Just put the code blocks in those #if defined CONFIG || CONFIG blocks

**Comment by steev** [comment]
0xdead...->0 is correct.

**Comment by davidgiven** [comment]
Thinking about it, I can actually do some refactoring to clean up and simplify a bit, and reduce the amount of evil #ifdefing a bit, so I'll do that and resubmit.

**Pull request closed without merging**
